@isTest
public class OrderExtension_OrderItemsTests {
	@isTest private static void testPopulateOrderItemListShouldCreateNewOrderItemsIfItemsAreNotInOrderItemByProductMap() {/* TODO */}
	@isTest private static void testPopulateOrderItemListShouldCreateOrderItemList() {/* TODO */}
	@isTest private static void testPopulateOrderItemListShouldIgnorePricebookEntriesWithoutProductId() {/* TODO */}
	@isTest private static void testBuildOrderItemListByDmlOperationMapShouldSeparateRecordsForUpsertFromRecordsForDeletion() {/* TODO */}
	@isTest private static void testPreserveValuesShouldTranscribeOrderQuantitiesIntoMap() {/* TODO */}
	@isTest private static void testSaveOrderItemsShouldReturnFalseOnFailure() {/* TODO */}
	@isTest private static void testSaveOrderItemsShouldUpsertAndDeleteOrderItems() {/* TODO */}
	@isTest private static void testUpsertOrderItemsShouldReturnFalseOnFailure() {/* TODO */}
	@isTest private static void testUpsertOrderItemsShouldUpsertAndDeleteOrderItems() {/* TODO */}
	@isTest private static void testDeleteOrderItemsShouldReturnFalseOnFailure() {/* TODO */}
	@isTest private static void testDeleteOrderItemsShouldUpsertAndDeleteOrderItems() {/* TODO */}
}