@isTest
public class OrderExtensionIntTest {
	@isTest private static void testGetStandardControllerShouldReturnPriceBookEntryController() {/* TODO */}
	@isTest private static void testSetOrderRecordShouldSetControllerRecordToUpdatedOrderRecordWhenRecordHasId() {/* TODO */}
	@isTest private static void testSetOrderRecordShouldSetControllerRecordToCurrentOrderRecordWhenRecordHasNoId() {/* TODO */}
	@isTest private static void testResetStandardSetControllerShouldReselectPricebookEntryItemsForSelectedFamily(){/* TODO */}
	@isTest private static void testFirstShouldMovePageToFirstPriceBookEntryValuesAndUpdateList(){/* TODO */}
	@isTest private static void testNextShouldMovePageToNextPriceBookEntryValuesAndUpdateList(){/* TODO */}
	@isTest private static void testPreviousShouldMovePageToPreviousPriceBookEntryValuesAndUpdateList(){/* TODO */}
	@isTest private static void testLastShouldMovePageToLastPriceBookEntryValuesAndUpdateList(){/* TODO */}
	@isTest private static void testGetHasPreviousShouldIndicateWhetherControllerHasPreviousValuesAndUpdateList(){/* TODO */}
	@isTest private static void testGetHasNextShouldIndicateWhetherControllerHasNextValuesAndUpdateList(){/* TODO */}
	@isTest private static void testGetTotalPagesShouldReturnNumberOfPagesRequiredToDisplayAllRows(){/* TODO */}
	@isTest private static void testGetPageNumberShouldReturnCurrentPageNumber(){/* TODO */}
	@isTest private static void testQueryOrderRecordShouldGetRecordForIndicatedId(){/* TODO */}
    
}