@isTest
public class OrderExtension_OrderRecordTests {
	@isTest private static void testSetOrderRecordShouldNotThrowExceptionWhenStandardControllerHasNotBeenSet() {/* TODO */}
	@isTest private static void testSetOrderRecordShouldSetControllerRecordToCurrentOrderRecordWhenRecordHasNoId() {/* TODO */}
	@isTest private static void testSetOrderRecordShouldSetControllerRecordToUpdatedOrderRecordWhenRecordHasId() {/* TODO */}
	@isTest private static void testQueryOrderRecordShouldGetRecordForIndicatedId(){/* TODO */}
	@isTest private static void testSelectOrderRecordShouldSelectRecordForId() {/* TODO */}
	@isTest private static void testSaveOrderRecordShouldReturnFalseOnFailure() {/* TODO */}
	@isTest private static void testSaveOrderRecordShouldUpsertOrderIntoStandardPricebook() {/* TODO */}
}