@isTest
public class OrderExtension_ProductTests {
	@isTest private static void testGetOrderItemProductIdShouldReturnNullIfPricebookEntryProductIdNotAvailable() {/* TODO */}
	@isTest private static void testGetOrderItemProductIdShouldReturnOrderItemPricebookEntryProductIdIfProductIdNotAvailable() {/* TODO */}
	@isTest private static void testGetOrderItemProductIdShouldReturnOrderItemProductIdIfAvailable() {/* TODO */}
	@isTest private static void testGetFamilyOptionsShouldReturnOptionsForProductFamily() {/* TODO */}
	@isTest private static void testSelectFamilyShouldResetControllerAndRepopulateOrderItemList() {/* TODO */}
	@isTest private static void testRefreshPieChartShouldAddOrderItemRecordsToPieChart() {/* TODO */}
	@isTest private static void testAddToPieChartShouldAddOrderItemRecordToPieChart() {/* TODO */}
	@isTest private static void testAddToPieChartShouldNotAddRecordsWithoutQuantity() {/* TODO */}
}