@isTest
public class Product2HelperTest {
	@isTest public static void testGetCollaborationGroupShouldReturnCollaborationGroup() {/* TODO */}
	@isTest public static void testGetCollaborationGroupShouldReturnCollaborationGroup() {/* TODO */}
	@isTest public static void testSelectInventoryAnnouncementCollaborationGroupShouldReturnCollaborationGroup() {/* TODO */}
    
	@isTest public static void testAfterUpdateShouldPostAnnouncements() {/* TODO */}
	@isTest public static void testOnAfterUpdateShouldPostAnnouncementsWhenQuantityIsLessThanThreshold() {/* TODO */}
	@isTest public static void testOnAfterUpdateShouldNotPostAnnouncementsWhenQuantityIsAtThreshold() {/* TODO */}
	@isTest public static void testOnAfterUpdateShouldNotPostAnnouncementsWhenQuantityIsAboveThreshold() {/* TODO */}

	@isTest public static void testGetFamilyOptionsShouldReturnProductFamilyPicklistAsSelectOptions() {/* TODO */}

	@isTest public static void testPostAlertsShouldPostAlerts() {/* TODO */}
	@isTest public static void testDoPostAlertsShouldPostAlerts() {/* TODO */}
	
	@isTest public static void testCreateTextSegmentInputShouldCreateTextSegmentInput() {/* TODO */}
	@isTest public static void testCreateMessageBodyInputShouldCreateMessageBodyInput() {/* TODO */}
	@isTest public static void testCreateAnnouncementInputShouldCreateAnnouncementInput() {/* TODO */}
}